# Demo

ref: http://christopher5106.github.io/deep/learning/2015/09/04/Deep-learning-tutorial-on-Caffe-Technology.html

In [1]:
import os
import sys

NOTEBOOK_PATH = os.getcwd()
FASTER_RCNN_PATH = NOTEBOOK_PATH + "/../py-faster-rcnn/"
CAFFE_PATH = FASTER_RCNN_PATH + "caffe-fast-rcnn/python"

sys.path.append(FASTER_RCNN_PATH)
sys.path.append(CAFFE_PATH)

import caffe

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

In [3]:
caffe.set_mode_cpu()

In [22]:
net = caffe.Net('conv.prototxt', caffe.TEST)

In [23]:
print net.blobs['conv'].data.shape

(1, 3, 96, 96)


In [24]:
im = np.array(Image.open("./cat_gray.jpg"))
im_input = im[np.newaxis, np.newaxis, :, :]
net.blobs['data'].reshape(*im_input.shape)
net.blobs['data'].data[...] = im_input

print net.blobs['data'].data.shape
print net.blobs['data'].data[...]

(1, 1, 360, 480)
[[[[  26.   27.   25. ...,   45.   50.   56.]
   [  26.   27.   25. ...,   50.   52.   58.]
   [  26.   27.   26. ...,   52.   55.   60.]
   ..., 
   [  36.   32.   36. ...,  182.  188.  190.]
   [  42.   42.   44. ...,  193.  184.  193.]
   [  46.   49.   52. ...,  214.  183.  183.]]]]


In [25]:
net.forward()

{'conv': array([[[[  674.,   678.,   677., ...,  1347.,  1339.,  1361.],
          [  672.,   671.,   669., ...,  1432.,  1428.,  1446.],
          [  674.,   670.,   669., ...,  1521.,  1518.,  1528.],
          ..., 
          [  956.,   954.,   972., ...,  4977.,  4880.,  4825.],
          [  971.,   979.,   996., ...,  5084.,  4976.,  4921.],
          [ 1046.,  1067.,  1082., ...,  5131.,  4994.,  4893.]],
 
         [[  674.,   678.,   677., ...,  1347.,  1339.,  1361.],
          [  672.,   671.,   669., ...,  1432.,  1428.,  1446.],
          [  674.,   670.,   669., ...,  1521.,  1518.,  1528.],
          ..., 
          [  956.,   954.,   972., ...,  4977.,  4880.,  4825.],
          [  971.,   979.,   996., ...,  5084.,  4976.,  4921.],
          [ 1046.,  1067.,  1082., ...,  5131.,  4994.,  4893.]],
 
         [[  674.,   678.,   677., ...,  1347.,  1339.,  1361.],
          [  672.,   671.,   669., ...,  1432.,  1428.,  1446.],
          [  674.,   670.,   669., ...,  152

In [26]:
net.save('cat.caffemodel')

In [28]:
# weights
print net.params['conv'][0].data.shape
print net.params['conv'][0].data[...]
print net.params['conv'][1].data.shape
print net.params['conv'][1].data[...]

(3, 1, 5, 5)
[[[[ 1.  1.  1.  1.  1.]
   [ 1.  1.  1.  1.  1.]
   [ 1.  1.  1.  1.  1.]
   [ 1.  1.  1.  1.  1.]
   [ 1.  1.  1.  1.  1.]]]


 [[[ 1.  1.  1.  1.  1.]
   [ 1.  1.  1.  1.  1.]
   [ 1.  1.  1.  1.  1.]
   [ 1.  1.  1.  1.  1.]
   [ 1.  1.  1.  1.  1.]]]


 [[[ 1.  1.  1.  1.  1.]
   [ 1.  1.  1.  1.  1.]
   [ 1.  1.  1.  1.  1.]
   [ 1.  1.  1.  1.  1.]
   [ 1.  1.  1.  1.  1.]]]]
(3,)
[ 1.  1.  1.]


In [29]:
# data
print net.blobs['conv'].data.shape
print net.blobs['conv'].data[...]

(1, 3, 356, 476)
[[[[  674.   678.   677. ...,  1347.  1339.  1361.]
   [  672.   671.   669. ...,  1432.  1428.  1446.]
   [  674.   670.   669. ...,  1521.  1518.  1528.]
   ..., 
   [  956.   954.   972. ...,  4977.  4880.  4825.]
   [  971.   979.   996. ...,  5084.  4976.  4921.]
   [ 1046.  1067.  1082. ...,  5131.  4994.  4893.]]

  [[  674.   678.   677. ...,  1347.  1339.  1361.]
   [  672.   671.   669. ...,  1432.  1428.  1446.]
   [  674.   670.   669. ...,  1521.  1518.  1528.]
   ..., 
   [  956.   954.   972. ...,  4977.  4880.  4825.]
   [  971.   979.   996. ...,  5084.  4976.  4921.]
   [ 1046.  1067.  1082. ...,  5131.  4994.  4893.]]

  [[  674.   678.   677. ...,  1347.  1339.  1361.]
   [  672.   671.   669. ...,  1432.  1428.  1446.]
   [  674.   670.   669. ...,  1521.  1518.  1528.]
   ..., 
   [  956.   954.   972. ...,  4977.  4880.  4825.]
   [  971.   979.   996. ...,  5084.  4976.  4921.]
   [ 1046.  1067.  1082. ...,  5131.  4994.  4893.]]]]
